query downloadAppQuery{
  downloadApps{
    data{
      attributes{
        Country
        Flag{
          data{
            attributes{
              url
            }
          }
        }
        GooglePlayLink
        AppStoreLink
      }
    }
  }
}