query getStartedQuery {
  getStarteds{
    data{
      attributes{
        title
        description
        content
        category
        image{
          data{
            attributes{
              url
            }
          }
        }
      }
    }
  }
}