query newsQuery{
  newsBlogs{
    data{
      attributes{
        title
        slug
        content
        publishedAt
        image{
          data{
            attributes{
              url
            }
          }
        }
      }
    }
  }
}